name: scripts manual
on:
  push:
    branches: [ main ]

jobs:
  ejecutar-scripts:
    runs-on: ubuntu-latest

    

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Script 1
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }} 
        
      run: |
        python scrap.py
        
    - name: Ejecutar Script 2
      env:
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }} 
      run: |
        python scrap2.py
